baseURL = "https://sosariaunbound.github.io/"
languageCode = "en-us"
title = "Sosaria Unbound"
theme = "minimal"


[params]
    author = "Sosaria Unbound"
    description = "Campaign Website for Sosaria Unbound"
    githubUsername = "sosaria-unbound"
    accent = "#e5c95c"
    showBorder = true
    backgroundColor = "#181815"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/campaign/"
    name = "Campaign"
    weight = 2

[[menu.main]]
    url = "/characters/"
    name = "Characters"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:sosariaunbound@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/sosaria-unbound/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/sosaria_unbound/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://app.roll20.net/lfg/listing/64532/sosaria-unbound"
    name = "rebel"
    weight = 4
